# Generated by Django 5.2.3 on 2025-06-26 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=5000, verbose_name='Название')),
                ('price_original', models.FloatField(verbose_name='Цена')),
                ('price', models.FloatField(verbose_name='Цена co скидкой')),
                ('rating', models.IntegerField(verbose_name='Рейтинг')),
                ('review_amount', models.IntegerField(verbose_name='Количество отзывов')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'db_table': 'product',
            },
        ),
    ]
